name: Run Brainrot Song Scrape Every 3 Hours

on:
  schedule:
    - cron: "0 */3 * * *"   # Runs every 3 hours
    - cron: "30 1-23/3 * * *"  # Runs every 3 hours
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:  
          python-version: "3.10"  # Specify the required Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install required libraries

      - name: Debug environment variables
        run: env | grep SPOTIPY
        env:
          SPINITRON_API_KEY: ${{ secrets.SPINITRON_API_KEY }}
          SPOTIPY_SCOPE: ${{ secrets.SPOTIPY_SCOPE }}
          SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_SECRET: ${{ secrets.SPOTIPY_SECRET }}
          REDIRECT_URI: ${{ secrets.redirect_uri }}  # Adjusted naming for consistency

      - name: Run script
        env:
          SPINITRON_API_KEY: ${{ secrets.SPINITRON_API_KEY }}
          SPOTIPY_SCOPE: ${{ secrets.SPOTIPY_SCOPE }}
          SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_SECRET: ${{ secrets.SPOTIPY_SECRET }}
          REDIRECT_URI: ${{ secrets.redirect_uri }}
        run: python spin_to_spotify.py
